import { randomBytes } from 'node:crypto';
import { normalizeEmail } from '../../account';

// Spec: SECURITY.md#sign-in-and-passwords — temporary passwords are generated by the server, never
// typed: 16 characters from a cryptographic random source, in Crockford base32, shown as
// `XXXX-XXXX-XXXX-XXXX`. That is 19 characters, inside the password rule's 12 to 128, and it has
// no `@`, so it can never be an email. Shown once to the person who created or reset the account;
// only its hash is stored. Nothing in this file logs, and errors never carry the password.

/** Crockford base32: digits and capitals without I, L, O and U, so it reads back unambiguously. */
export const CROCKFORD_BASE32 = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

const CHARACTERS = 16;
const GROUP = 4;

/** `XXXX-XXXX-XXXX-XXXX` in Crockford base32. */
export const TEMPORARY_PASSWORD_PATTERN = /^[0-9A-HJKMNP-TV-Z]{4}(?:-[0-9A-HJKMNP-TV-Z]{4}){3}$/;

/** A new temporary password, `XXXX-XXXX-XXXX-XXXX`: 16 random Crockford base32 characters. */
export function generateTemporaryPassword(): string {
  // 32 divides 256, so taking the low 5 bits of each byte keeps every character equally likely.
  const bytes = randomBytes(CHARACTERS);
  let password = '';
  for (let index = 0; index < CHARACTERS; index += 1) {
    if (index > 0 && index % GROUP === 0) password += '-';
    password += CROCKFORD_BASE32[(bytes[index] ?? 0) & 31];
  }
  return password;
}

/**
 * A new temporary password for the account with `email`. The password rule says a password must
 * differ from the email; a generated one has no `@` and can't match, but the rule is checked, not
 * assumed.
 */
export function generateTemporaryPasswordFor(email: string): string {
  const account = normalizeEmail(email);
  for (;;) {
    const password = generateTemporaryPassword();
    if (normalizeEmail(password) !== account) return password;
  }
}
