import { businessToday } from '../../dates';
import { findGeneratedFile, type StoredFile } from '../files/stored-files';
import { describeJobError } from './connection';
import { DEV_PING_JOB, DEV_SAMPLE_EXPORTS_JOB, devSampleExportKeys } from './dev-jobs';
import { type JobRunState, waitForJob } from './health';
import { enqueueJob } from './queue';

// Job checks for the development `/dev/health` page (build step 0.7): a test job through the
// worker, and the sample PDF and Excel files generated by a job. Run only when Redis is connected
// and a worker is up.

export interface DevJobChecks {
  testJob: JobRunState | { state: 'error'; error: string };
  sampleExports: JobRunState | { state: 'error'; error: string } | null;
  sampleFiles: { pdf: StoredFile | null; xlsx: StoredFile | null } | null;
}

async function run(
  enqueue: () => Promise<{ id: string }>,
  timeoutMs: number,
): Promise<JobRunState | { state: 'error'; error: string }> {
  try {
    const job = await enqueue();
    return await waitForJob(job.id, timeoutMs);
  } catch (error) {
    return { state: 'error', error: describeJobError(error) };
  }
}

/**
 * Enqueues `dev.ping` and waits for it, then (with a database) enqueues `dev.sampleExports` for
 * today. That job is idempotent, so every reload runs it again and gets the same two files back.
 */
export async function runDevJobChecks({ database }: { database: boolean }): Promise<DevJobChecks> {
  const testJob = await run(() => enqueueJob(DEV_PING_JOB, { failAttempts: 0 }), 5_000);
  if (!database) return { testJob, sampleExports: null, sampleFiles: null };

  const day = businessToday();
  const sampleExports = await run(() => enqueueJob(DEV_SAMPLE_EXPORTS_JOB, { day }), 20_000);
  const keys = devSampleExportKeys(day);
  try {
    const [pdf, xlsx] = await Promise.all([
      findGeneratedFile(keys.pdf),
      findGeneratedFile(keys.xlsx),
    ]);
    return { testJob, sampleExports, sampleFiles: { pdf, xlsx } };
  } catch (error) {
    return {
      testJob,
      sampleExports: { state: 'error', error: describeJobError(error) },
      sampleFiles: null,
    };
  }
}
